###################
#
# Functions to process MAGEMin julia structures
#
###################

JuliaStructToList <- function(julia_object){
  #' Ancillary function to convert a complex julia struct to a R list
  #' @details Simple types (vectors of atomic types, etc) will be converted to 
  #' R equivalents, but more complex types will be returned as a JuliaObject
  #' that the user would need to manually process
  #' @param julia_object A Julia struct (made of several fields)
  #' @returns A R list with the content of the input object
  #' @import JuliaCall
  #' @export
  
  fieldNames <- fields(julia_object)
  
  ret<- lapply(fieldNames,
               FUN=function(ii){
                 field(julia_object,ii)  
               }
  )
  names(ret) <- fieldNames
  return(ret)
}

# # WiP
# An attempt to recursively unpck a julia object...
# JuliaVectToList <- function(julia_object){
#   
#   VecNElts <- as.integer(julia_object$size)
# 
#   ret<- lapply(1:VecNElts,
#                FUN=function(ii){
#                  current_object <- julia_eval(paste0('out.SS_vec[',i,'];'))
#                  JuliaStructToList(current_phase)
#                  
#                }
#   )
# }


getPhProp <- function(MMo){
  #' Return a named vector with phase proportions
  #' @param MMo A R object with MAGEMin data, probably generated by MAGEMin()
  #' @returns A named vector of phase proportions
  #' @export
  
  phn <- MMo$ph
  phprop <- MMo$ph_frac
  names(phprop) <- phn
  
  return(phprop)
}

getSSComp <- function(MMo,phName,unit="wt"){
  #' Extract the composition of a solid solution phase from MAGEMin results
  #' @param MMo A R object with MAGEMin data, probably generated by MAGEMin()
  #' @param phName The name of the phase to extract
  #' @param unit c("mol","wt","apfu","emmol","emwt") Unit in which the composition is expressed:
  #' can be moles, weight, atom per formula unit or end-member proportions (in mol or wt).
  #' @returns A named vector of phase composition
  #' @export
  
  # If there are no solutions, do nothing !
  nn<-unlist(MMo$SS_syms[phName])
  if(!is.null(nn)){
    # Decide on the fields to use, depending on system units
    nm <- switch(unit,
                    mol = MMo$oxides,
                     wt = MMo$oxides,
                   apfu = MMo$oxides,
                  emmol = MMo$SS_vec[[nn]]$emNames,
                   emwt = MMo$SS_vec[[nn]]$emNames
                     )
    phComp <- switch(unit,
                     mol = MMo$SS_vec[[nn]]$Comp,
                     wt = MMo$SS_vec[[nn]]$Comp_wt,
                     apfu = MMo$SS_vec[[nn]]$Comp_apfu,
                     emmol = MMo$SS_vec[[nn]]$emFrac,
                      emwt = MMo$SS_vec[[nn]]$emFrac_wt,
    )
    names(phComp) <- nm   
    return(phComp)}
  else{
    return(NA)
  }
}


